// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgYrR88tVorqOPTf4GWFSV8hMbbCl5A1k',
    appId: '1:292323030316:web:ed89809d59b46357446889',
    messagingSenderId: '292323030316',
    projectId: 'fashion-store-c92ce',
    authDomain: 'fashion-store-c92ce.firebaseapp.com',
    storageBucket: 'fashion-store-c92ce.appspot.com',
    measurementId: 'G-YHCQ4CRVHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCavhx2jKhuSdDMY0f2hHRgE1APn1z4_Q',
    appId: '1:292323030316:android:c582b83b16aab9d0446889',
    messagingSenderId: '292323030316',
    projectId: 'fashion-store-c92ce',
    storageBucket: 'fashion-store-c92ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnfPksD0t7by_rNd2FL5_hKqfIxlbLd0',
    appId: '1:292323030316:ios:e76e0c783bf1164b446889',
    messagingSenderId: '292323030316',
    projectId: 'fashion-store-c92ce',
    storageBucket: 'fashion-store-c92ce.appspot.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnfPksD0t7by_rNd2FL5_hKqfIxlbLd0',
    appId: '1:292323030316:ios:e76e0c783bf1164b446889',
    messagingSenderId: '292323030316',
    projectId: 'fashion-store-c92ce',
    storageBucket: 'fashion-store-c92ce.appspot.com',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgYrR88tVorqOPTf4GWFSV8hMbbCl5A1k',
    appId: '1:292323030316:web:f11965393e370301446889',
    messagingSenderId: '292323030316',
    projectId: 'fashion-store-c92ce',
    authDomain: 'fashion-store-c92ce.firebaseapp.com',
    storageBucket: 'fashion-store-c92ce.appspot.com',
    measurementId: 'G-9TGE221RLN',
  );
}
